### ISSUE TITLE
Bibliography name does not appear in header.

### ISSUE THREAD

**Issue by adityasole** [COPCSE-NTNU/thesis-NTNU#10]
Bibliography name does not appear in header.

**Comment by ifarup** [comment]
The same goes for table of contents (if it spans several pages), list of figures etc. Probably for all unnumbered chapters (\chapter*{})

**Comment by ifarup** [comment]
Can you verify that it works now?

**Comment by adityasole** [comment]
Yes, this works perfect now. Thank you 😊.
