### ISSUE TITLE
Should perhaps glossary references be colored in printed documents?

### ISSUE THREAD

**Issue by barskern** [COPCSE-NTNU/thesis-NTNU#23]
Currently glossary entries are not highlighted, however in digital documents a link is created using `hyperref` (mathematics is the glossary reference here).

![bilde](https://user-images.githubusercontent.com/14995334/81947619-0fa7a480-9601-11ea-8153-a31a92bcfb8a.png)

When printing the document, should perhaps glossary items be a different color to show the user that the word is explained in the glossary? Or should glossaries simply be anonymous in regular text? What is the best practice?

**Comment by ifarup** [comment]
Well, this is a matter of preference. Personally, I prefer coloured (blue) links when I read on a display (when links can be clicked), and black cross references on print. We had to select one, and went for print priority, i.e., black for all links. This can easily be overridden by the user by altering the \hypersetup (near the end of ntnuthesis.cls) in the preamble.
