### ISSUE TITLE
New pages after almost every chapter

### ISSUE THREAD

**Issue by martvo** [COPCSE-NTNU/thesis-NTNU#25]
I have been noticing all the empty pages after every chapter, and now I can see the every chapter is followed by an empty page expect one. I was looking around in ntnuthesis.cls and removed \RequirePackage{emptypage} to see what difference it would make and then I saw that every empty page has the same header as the chapter before it. What causes the new pages to be added to the end of every chapter and can it be omitted since it seems to not work?

**Comment by ifarup** [comment]
If I understand your problem correctly, this is a feature and not a bug. With the `twoside` class option (default), the layout is meant for duplex printing with every chapter starting on the right hand side, i.e., on an oddly numbered page. If you don't like this, use the `oneside` class option instead. See also issue #1 .
