### ISSUE TITLE
Normal paragraphs do not have any spacing or indentation to separate them from each other

### ISSUE THREAD

**Issue by morngrar** [COPCSE-NTNU/thesis-NTNU#26]
The `\parskip` and `\parindent` commands do nothing, it seems; and I've tried setting their lengths manually both in the preamble and inside the class file. As it stands now, there isn't any separation between paragraphs. Is this intentional? Personally I find this quite hard to read, and whish I was able to change it. I'll dig around more and try to find a solution.

**Comment by morngrar** [comment]
Removing this part:

```
% Renew \lstlistoflistings command to avoid issues with incorrect headers for long lists
% Uses unnumbered chapter instead of a float like in the original source code.
% Based on source code for listings package https://ctan.uib.no/macros/latex/contrib/listings/listings.dtx line: 14635
\renewcommand*{\lstlistoflistings}{%
       \chapter*{\lstlistlistingname}%
       \parskip\z@\parindent\z@\parfillskip \z@ \@plus 1fil%
       \@starttoc{lol}%
       }%
```

At the bottom of the class file solved the paragraph problem. There is something with this code that messes things up..

**Comment by morngrar** [comment]
Found the issue. The command above changes the parskip and parindent values, so that the list of listings is rendered nicely, however it doesn't reset them afterwards, so it messes up the rest of the document.

The following demos this, setting these values to obscene dimensions everywhere but the listing toc:
```
% Renew \lstlistoflistings command to avoid issues with incorrect headers for long lists
% Uses unnumbered chapter instead of a float like in the original source code.
% Based on source code for listings package https://ctan.uib.no/macros/latex/contrib/listings/listings.dtx line: 14635
\renewcommand*{\lstlistoflistings}{%
       \chapter*{\lstlistlistingname}%
       \parskip\z@\parindent\z@\parfillskip \z@ \@plus 1fil%
       \@starttoc{lol}%
%% SETTING PARAGRAPH SPACINGS
\setlength{\parskip}{3em}
\setlength{\parindent}{2em}
       }%
```

**Comment by morngrar** [comment]
A simple solution is to set these values right underneath the `\lstlistoflistings` command in thesis.tex (around line 70 at the time of writing), however in my opinion this should rather be fixed in the class file, since that's where the error is. I'm unsure how to alter this command to preserve the pre-existing values, though.

**Comment by ifarup** [comment]
Strange. I wasn't aware of this one. I'll look into it.

**Comment by ifarup** [comment]
As you say, it is caused by the new definition of \lstlistoflistings. It was introduced in commit [79860f2f2d802000d18384720a68c3f08dc28c9f](https://github.com/COPCSE-NTNU/thesis-NTNU/commit/79860f2f2d802000d18384720a68c3f08dc28c9f) to solve another issue. Any suggestions, @Hexoplon? See #22
