### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by odinuge** [COPCSE-NTNU/thesis-NTNU#28]
In order to allow people to actually use this template and copy/clone this repo freely and modify it, it should contain information about what license it is distributed under (if any).

Also, there appears to be two papers in the `/papers` folder. What license are those distributed under, and where can that information be found?

**Comment by ifarup** [comment]
Very good points.

What would be the best license to use for the template? Personally, I generally prefer GPL for code and CC-BY-SA for documents at least when produced by publicly funded academic institutions. This repository contains both text and code, so I am a bit in doubt. Or, maybe: for general use in student projects, would be better to avoid the copyleft effects and rather go for MIT/BSD/CC-BY? Or perhaps the midway, LGPL?

I will look into the licenses for the attached papers. Depending on what we decide on the license for the template, we might need to find some other papers with compatible licenses to demonstrate that particular application of the template, i.e., PhD theses based on already published papers.

**Comment by odinuge** [comment]
Thanks for the thorough answer @ifarup! 

> What would be the best license to use for the template? Personally, I generally prefer GPL for code and CC-BY-SA for documents at least when produced by publicly funded academic institutions. This repository contains both text and code, so I am a bit in doubt. Or, maybe: for general use in student projects, would be better to avoid the copyleft effects and rather go for MIT/BSD/CC-BY? Or perhaps the midway, LGPL?

My background is mostly working with various big and small open source projects, and I have no real knowledge about the academic part of this, and have never dealt with licenses of documents; so i might have some bias in that sense.

Since the purpose of this project is sharing a nice template to help students and other academic professionals (both at NTNU and others), I think an "open" and "free-for-all and use it as you want as long as you embed this license" is nice. The most important thing to me is that people can easily understand that they can use this without having to think about how/what/if.

I usually go for MIT for small projects, but Apache and BSD works more or less the same I guess (but again, most familiar with MIT). The normal thing with MIT is to embed the license into compiled binaries, and I am not sure how that works with pdfs, but I don't really think it is _that_ important.

Changing the license is however a bit iffy (since the old work is not licensed), since all contributors should in theory agree about it, but I don't think that is a big issue in this case. :smile: 

> I will look into the licenses for the attached papers. Depending on what we decide on the license for the template, we might need to find some other papers with compatible licenses to demonstrate that particular application of the template, i.e., PhD theses based on already published papers.

Yes! I see the purpose of the current papers, but they are currently being distributed without proper attribution (if their licenses require that), if they are licensed for this use at all. I guess not a lot of papers are licensed under MIT, so not sure about the best solution in this case... If they are licensed under CC-BY-SA it should work I guess, as long as they are attributed correctly.

**Comment by morngrar** [comment]
Be vary that there may be some underlying licenses restricting this choice in the used tex packages, and possibly even throughany tooling used to create the initial template for this. Licenses which are very latex specific. At least I've encountered this when hacking on bibtex.

**Comment by ifarup** [comment]
Interesting, and a bit disturbing... Which license or combination of lincenses cause such problems? We use quite a lot of packages here: pdfpages, inputenc, fontenc, mathdesign, berasans, DejaVuSansMono, listings, babel, geometry, enumitem, graphicx, amsmath, caption, subcaption, xcolor, emptypage, csquotes, biblatex, csvsimple, booktabs, gnuplottex, hyperref, cleveref, glossaries, as well as the standard LaTeX report class. Is it possible that we are doing something wrong already by combining them?

**Comment by odinuge** [comment]
Since this repo don't distribute the packages themselves, or the output you get when we/use them, I don't think that should be an issue.

I guess it is possible to disclose that in the README tho. if neccecary; that the license only applies to the files in the repo, and that the packages used may have other licenses that the users should be "aware of". I don't know the license of all those projects, but I still don't think it should be an issue.

**Comment by ifarup** [comment]
Good. So then we are back to selecting something that all the developers can agree on. Fortunately, we are not that many. So @marni @SimonMcCallum @Hexoplon @barskern @eirikeve @gtl-hig @orbekk do you agree to distribute the template under the MIT license? (hope I didn't forget any). Will need a like/thumbs up from all of you to proceed. Or a suggestion for some other action.

**Comment by morngrar** [comment]
> Interesting, and a bit disturbing... Which license or combination of lincenses cause such problems? We use quite a lot of packages here: pdfpages, inputenc, fontenc, mathdesign, berasans, DejaVuSansMono, listings, babel, geometry, enumitem, graphicx, amsmath, caption, subcaption, xcolor, emptypage, csquotes, biblatex, csvsimple, booktabs, gnuplottex, hyperref, cleveref, glossaries, as well as the standard LaTeX report class. Is it possible that we are doing something wrong already by combining them?

The specific example is using `makebst` to generate a bst-file for use with bibtex. The resulting file is subject to a license, also any modification or derivation of it is subject to it as well. Although the license is an open source license, it is a special beast commonly used within ctan, I believe, (ps. Just googled this now, and it's a version of the latex project public license) and I don't know how compatible or not it is with other licenses. If you are licensing this, being aware of the licensing of the constituent parts isn't a non-issue, given that there is quite [a lot of different licenses](https://ctan.org/license?lang=en) hanging around in the latex ecosystem.

**Comment by orbekk** [comment]
@ifarup Approved. You may distribute my contributions under the MIT license or any other license you decide.

**Comment by ifarup** [comment]
Totally forgot to follow up on this one. Would a change to an MIT licence be ok for you as well, @bilde2910 ?

**Comment by bilde2910** [comment]
That sounds good with me. I approve of my contributions to this repository being licensed and distributed under the MIT license.
