### ISSUE TITLE
Page number position not consistent

### ISSUE THREAD

**Issue by erlingrj** [COPCSE-NTNU/thesis-NTNU#42]
Thanks for this great template, I am using it to write my thesis. I am however having problems with getting the page numbers placed in a consistent manner. Now, for any page containing `\chapter` the page number is at the bottom, centerered. For other pages they are at the top right corner. 

I would like to have either all page numbers at the bottom center, or even numbers on left and odd numbers on right. Any suggestions for how to achieve this?

Thank you.

**Comment by ifarup** [comment]
Hi. Thanks for the feedback. Well, this is actually a feature, not a bug. It is in agreement with many (but not all) recommendations on typography for longer reports. You may also have noticed that empty pages at the end of chapters do not have page numbers at all if you use the twoside option. If you don't like the way it behaves, you may

- redefine the \ps@ntnuheadings in ntnuthesis.cls if you would like to change the headings of regular pages
- redefine the default \chapter macro that sets the pagestyle to plain for the first page of a chapter if you want headings on those pages as well
- remove the package emptypage from ntnuthesis.cls if you don't like the missing page number on empty pages

Cf. issues #25 and #1
