### ISSUE TITLE
Colour palette

### ISSUE THREAD

**Issue by ifarup** [COPCSE-NTNU/thesis-NTNU#5]
Design a colour palette and use it throughout for syntax highlighting in code listings, URLs, cross reference links etc.

**Comment by ifarup** [comment]
The coloured links work well on display, but not on print. Revert to the standard hyperref formatting?

**Comment by ifarup** [comment]
Perhaps add a package option 'print' which omits hyperref altogether? Coloured links do not make much sense on paper.

**Comment by adityasole** [comment]
Another idea would be to make the clickable links in Black colour.

**Comment by ifarup** [comment]
Good idea. Done. If the author wants it differently, he can change it in the document using \hypersetup{}.
